name: simple_auth_flutter
description: Simple Auth is the simplest way to authenticate your users/apis. This plugin will securely store tokens/credentials as well as automatically present login UI when needed.
version: 2.0.1
author: James Clancey <james.clancey@gmail.com>
homepage: https://github.com/clancey/simple_auth

environment:
    sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_auth:
    git:
      url: git://github.com/jeffosmith/simple_auth.git
      path: simple_auth
      ref: custom_token
flutter:
  plugin:
    androidPackage: clancey.simpleauth.simpleauthflutter
    pluginClass: SimpleAuthFlutterPlugin

dev_dependencies_overrides:
  simple_auth:
    git:
      url: git://github.com/jeffosmith/simple_auth.git
      path: simple_auth
      ref: custom_token
